module.exports = {
  development:{
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'',
    WAMPURL:'',
    WAMPREALM:'realm1',
    EXTENSIONS:[
      '.mp4',
      '.avi',
      '.mkv',
      '.mp3',
      '.cbz',
      '.cbr',
      '.pdf',
      '.chm',
      '.txt',
      '.epub',
      '.log'
    ]
  },
  testing:{
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'',
    WAMPURL:'',
    WAMPREALM:'',
    EXTENSIONS:[
      '.mp4',
      '.avi',
      '.mkv',
      '.mp3',
      '.cbz',
      '.cbr',
      '.pdf',
      '.chm',
      '.txt',
      '.epub',
      '.log'
    ]
  },
  production:{
    DBUSER:'root',
    DBHOST:'localhost',
    DBPASS:'',
    WAMPURL:'',
    WAMPREALM:'',
    EXTENSIONS:[
      '.mp4',
      '.avi',
      '.mkv',
      '.mp3',
      '.cbz',
      '.cbr',
      '.pdf',
      '.chm',
      '.txt',
      '.epub',
      '.log'
    ]
  }
};
