services:
  backend:
    image: docker.outlawdesigns.io/webaccessevents:arm
    environment:
      NODE_ENV: production
      DBHOST: localhost
      DBUSER: root
      DBPASS: example
      DBDB: web_access
      DBTABLE: requests
      WAMPURL: ws://localhost:8080
      WAMPREALM: realm1
      WAMPEVENTNAME: io.outlawdesigns.webaccess.fileDownloaded
      EXTENSIONS: ".mp4,.avi,.mkv,.mp3,.cbz,.cbr,.pdf,.chm,.txt,.epub,.log"
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /tmp/log/:/log/
